kind: pipeline
type: docker
name: screenshots-stable

steps:
  - name: gplay
    image: nextcloudci/android:android-49
    privileged: true
    environment:
      LOG_USERNAME:
        from_secret: LOG_USERNAME
      LOG_PASSWORD:
        from_secret: LOG_PASSWORD
      GIT_USERNAME:
        from_secret: GIT_USERNAME
      GIT_TOKEN:
        from_secret: GIT_TOKEN
      ORG_GRADLE_PROJECT_coverage: ''
    commands:
      - scripts/checkIfRunDrone.sh $GIT_USERNAME $GIT_TOKEN $DRONE_PULL_REQUEST || exit 0
      - emulator-headless -avd android-27 -no-snapshot -gpu swiftshader_indirect -no-window -no-audio -skin 500x833 &
      - sed -i s'#<bool name="is_beta">false</bool>#<bool name="is_beta">true</bool>#'g src/main/res/values/setup.xml
      - ./gradlew assembleGplayDebug
      - scripts/wait_for_emulator.sh
      - ./gradlew installGplayDebugAndroidTest
      - scripts/runAllScreenshotCombinations "stable" false
  - name: notify
    image: drillster/drone-email
    settings:
      port: 587
      from: nextcloud-drone@kaminsky.me
      recipients_only: true
      username:
        from_secret: EMAIL_USERNAME
      password:
        from_secret: EMAIL_PASSWORD
      recipients:
        from_secret: EMAIL_RECIPIENTS
      host:
        from_secret: EMAIL_HOST
    when:
      event:
        - push
      status:
        - failure
      branch:
        - master
trigger:
  branch:
    - master
  event:
    - push
    - pull_request
